### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by Uimix** [RelinRan/JPushSDK#1]
写的很nice，极光推送sdk官方会更新版本，作者会一直更新sdk吗，这样很多项目都能依赖，不用一个个去更新SDK版本啦。

**Comment by RelinRan** [comment]
会持续更新滴

**Comment by Uimix** [comment]
jpush，jcore版本作者能升级到最新版本吗？如果不能我只能参考作者的自己撸一个了。

**Comment by RelinRan** [comment]
目前是需要适配AndroidX吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Uimix"<notifications@github.com&gt;; 
发送时间: 2020年7月21日(星期二) 上午10:30
收件人: "RelinRan/JPushSDK"<JPushSDK@noreply.github.com&gt;; 
抄送: "梦雨秋生"<1101005304@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [RelinRan/JPushSDK] 版本问题 (#1)





 
jpush，jcore版本作者能升级到最新版本吗？如果不能我只能参考作者的自己撸一个了。

**Comment by Uimix** [comment]
那到没有，只是现在项目jcore版本都是2.3.8版本的，作者的才1.2.7, jpush也稍微低了点

**Comment by RelinRan** [comment]
中午进行更新




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Uimix"<notifications@github.com&gt;; 
发送时间: 2020年7月21日(星期二) 上午10:37
收件人: "RelinRan/JPushSDK"<JPushSDK@noreply.github.com&gt;; 
抄送: "梦雨秋生"<1101005304@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [RelinRan/JPushSDK] 版本问题 (#1)





 
那到没有，只是现在项目jcore版本都是2.3.8版本的，作者的才1.2.7, jpush也稍微低了点

**Comment by RelinRan** [comment]
已更新

**Comment by Uimix** [comment]
哈哈，看到了，官方文档说了JCore 是 2.0.0 及以上的版本，需要额外在 Androidmanifest 中配置一个Service，以在更多手机平台上获得更稳定的支持，作者好像没有加哦。

**Comment by RelinRan** [comment]
已增加




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Uimix"<notifications@github.com&gt;; 
发送时间: 2020年7月21日(星期二) 中午1:18
收件人: "RelinRan/JPushSDK"<JPushSDK@noreply.github.com&gt;; 
抄送: "梦雨秋生"<1101005304@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [RelinRan/JPushSDK] 版本问题 (#1)





 
哈哈，看到了，官方文档说了JCore 是 2.0.0 及以上的版本，需要额外在 Androidmanifest 中配置一个Service，以在更多手机平台上获得更稳定的支持，作者好像没有加哦。

**Comment by RelinRan** [comment]
已增加Service

**Comment by Uimix** [comment]
作者又埋了一个坑啊，哈哈，测试半天，发现作者还少注册了一个东西，导致消息监听 Tag/Alias操作监听 都监听不到，不知道作者测试过没有，JNotifyActivity，作者在看看。

**Comment by RelinRan** [comment]
我的错，最近有点忙，所有我换了没有测试。已添加。版本1.1.1




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Uimix"<notifications@github.com&gt;; 
发送时间: 2020年7月22日(星期三) 中午11:02
收件人: "RelinRan/JPushSDK"<JPushSDK@noreply.github.com&gt;; 
抄送: "梦雨秋生"<1101005304@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [RelinRan/JPushSDK] 版本问题 (#1)





 
作者又埋了一个坑啊，哈哈，测试半天，发现作者还少注册了一个东西，导致消息监听 Tag/Alias操作监听 都监听不到，不知道作者测试过没有，JNotifyActivity，作者在看看。

**Comment by Uimix** [comment]
还有为什么Tag/Alias操作监听的消息一直在无限发，不是应该在真正有操作的时候在发吗，这个是不是得优化一下，消息监听我还在测，感觉好像也有点问题。。。

**Comment by RelinRan** [comment]
这个是需要一直监听滴 存在掉线的情况。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Uimix"<notifications@github.com&gt;; 
发送时间: 2020年7月22日(星期三) 中午11:18
收件人: "RelinRan/JPushSDK"<JPushSDK@noreply.github.com&gt;; 
抄送: "梦雨秋生"<1101005304@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [RelinRan/JPushSDK] 版本问题 (#1)





 
还有为什么Tag/Alias操作监听的消息一直在无限发，不是应该在真正有操作的时候在发吗，这个是不是得优化一下，消息监听我还在测，感觉好像也有点问题。。。

**Comment by Uimix** [comment]
Required SDK核心功能 since 3.3.0
        <activity
            android:name="cn.jpush.android.service.JNotifyActivity"
            android:exported="true"
            android:taskAffinity="jpush.custom"
            android:theme="@android:style/Theme.Translucent.NoTitleBar">
            <intent-filter>
                <action android:name="cn.jpush.android.intent.JNotifyActivity" />
                <category android:name="${applicationId}" />
            </intent-filter>
        </activity>

**Comment by Uimix** [comment]
Required SDK核心功能 since 3.3.0
        <activity
            android:name="cn.jpush.android.service.JNotifyActivity"
            android:exported="true"
            android:taskAffinity="jpush.custom"
            android:theme="@android:style/Theme.Translucent.NoTitleBar">
            <intent-filter>
                <action android:name="cn.jpush.android.intent.JNotifyActivity" />
                <category android:name="${applicationId}" />
            </intent-filter>
        </activity>

**Comment by Uimix** [comment]
cn.jpush.android.service.JNotifyActivity  这个东西不注册收不到通知

**Comment by RelinRan** [comment]
你急的话，就暂时按官方集成，这几天有点忙；我后面测试好了会最终更新一次



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Uimix"<notifications@github.com&gt;; 
发送时间: 2020年7月22日(星期三) 中午11:50
收件人: "RelinRan/JPushSDK"<JPushSDK@noreply.github.com&gt;; 
抄送: "梦雨秋生"<1101005304@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [RelinRan/JPushSDK] 版本问题 (#1)





 
cn.jpush.android.service.JNotifyActivity  这个东西不注册收不到通知

**Comment by Uimix** [comment]
好的，目前也用不到你的消息监听，我自己写个自定义广播。
